version: "3"
services: 
  nginx-google:
    build: "."
    container_name: "nginx-google"
    restart: "always"
    volumes: 
      - "./nginx-google-log:/var/log/nginx/"
      - "./nginx.conf:/usr/local/nginx/conf/nginx.conf"
    ports: 
      - "8082:80"
